server:
  port: 8071
  
spring:
  application:
    name: "config-server"
    profiles:
      active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/orcuncolak/spring-cloud-config-server-git-tutorial
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          order: 2